title: MENG DE's Homepage
logo: /assets/img/image97.gif
description: Meng De, Msc <br /> A student in HongKong University <br />Contact me by mengde@connect.hku.hk
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
