title: MENG DE's Homepage
logo: <img src="./pf3.jpg" width = "160" height = "160" alt="profile" />
description: Meng De, Msc <br /> A student in HongKong University <br />Contact me by mengde@connect.hku.hk
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
